<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>AutoEmuControllerConfig</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Baselines/*" />
    <InternalsVisibleTo Include="AutoEmuControllerConfig.Tests" />
  </ItemGroup>
</Project>
